# Generated by Django 5.0.2 on 2024-03-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
        ('land', '0003_alter_land_time_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyland',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='land.land'),
        ),
    ]
