# Generated by Django 5.0.2 on 2024-03-08 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_buyland_land'),
        ('house', '0005_house_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyland',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
    ]
