# Generated by Django 5.0.2 on 2024-03-03 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('area_sqft', models.FloatField()),
                ('description', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='land_photos/')),
                ('video_tour', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('reason_for_selling', models.TextField(blank=True, null=True)),
                ('plot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('time_line', models.CharField(blank=True, default='Not Available', max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
