# Generated by Django 5.0.2 on 2024-03-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='time_line',
            field=models.DateField(blank=True, default='Not Available', max_length=100, null=True),
        ),
    ]
