# Generated by Django 5.0.2 on 2024-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='house_photos/'),
        ),
        migrations.AddField(
            model_name='house',
            name='video_tour',
            field=models.URLField(blank=True, null=True),
        ),
    ]
