# Generated by Django 5.0.2 on 2024-03-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_house_bathrooms_alter_house_bedrooms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HouseLease',
        ),
    ]
