# Generated by Django 5.0.2 on 2024-03-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_delete_houselease'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
